### ISSUE TITLE
Whitening stabilization of Pykilosort

### ISSUE THREAD

**Issue by chris-langfield** [int-brain-lab/pykilosort#14]
- [x] Run PyKS with default threshold (but updated whitening) on at least: 16ad, 5f77

- [x] Look at whitening matrix diagonals

- [ ] make sure bad channels are output by Pykilosort (if no dataset type, create or document how to get info from dataset)
Recompute condition number of WM without faulty channels

**Comment by chris-langfield** [comment]
PyKS was rerun with default threshold but new whitening for apples to apples comparison.

- Condition number blows up for new whitening unless you remove out-of-brain channels
- 16ad is affected by this as one channel (255) is labeled in brain but perhaps should be out of brain. Have to manually remove this channel from histology to get WM to behave

**Comment by chris-langfield** [comment]
PyKS does save the IDs of noisy, dead, out-of-brain channels in `channel_maps.npy`, though this doesn't appear to be included in the `_kilosort.raw_output` dataset type

https://github.com/int-brain-lab/pykilosort/blob/dae7d4b3d815b701c5c9f797848bd4340f338d4e/pykilosort/postprocess.py#L1480

**Comment by chris-langfield** [comment]
https://github.com/int-brain-lab/ibllib/issues/615

**Comment by oliche** [comment]
For the output of bad channels, we'll add this to the output format description of Dartsort
