### ISSUE TITLE
get_good_channels argument order and method setting

### ISSUE THREAD

**Issue by louiskang** [int-brain-lab/pykilosort#19]
Hi, I'm new to the experimental world, but it appears that there's a bug related to `get_good_channels`. In particular, in line 95 of `pykilosort/main.py`, the order of arguments is `get_good_channels(raw_data, params, probe)` but in the function definition in line 278 `pykilosort/preprocess.py`, the order of arguments is `get_good_channels(raw_data, probe, params)`.

One possible resolution is to
1. change line 96 in `pykilosort/main.py` to `raw_data, probe, params ...`
2. change line 285 in `pykilosort/preprocess.py` to `... raw_data, probe, params ...`
3. reorder lines 289 and 290 in `pykilosort/preprocess.py`

The IBL bad channels detection method isn't working for my dataset, and I was experimenting with using the kilosort method, which does seem to work. Would you consider allowing the user to select the detection method as a parameter in the pykilosort call? If so, could you modify `get_good_channels_kilosort` in line 311 of `pykilosort/preprocess.py` to return `channels_labels` in addition to `good_channels`? `probe.channels_labels` get used later in pykilosort postprocessing.

Thanks for all the good work!

**Comment by chris-langfield** [comment]
Hi @louiskang. Yes, those function signatures are confusing, I'll update them for clarity. 

Feel free to make a PR with the changes you're describing and we can take a look :) 

Thanks!

**Comment by chris-langfield** [comment]
Closed by #23 see release 1.4.7
