### ISSUE TITLE
Invalid version: 'ibl_1.4.5'.

### ISSUE THREAD

**Issue by Virginia9733** [int-brain-lab/pykilosort#21]
Hi there, 

When I tried to install pykilosort, I encountered this error message: "Invalid version: 'ibl_1.4.5"

(si) d:\repos>git clone --branch ibl_prod https://github.com/int-brain-lab/pykilosort
Cloning into 'pykilosort'...
remote: Enumerating objects: 2536, done.
remote: Counting objects: 100% (958/958), done.
remote: Compressing objects: 100% (355/355), done.
remote: Total 2536 (delta 672), reused 857 (delta 601), pack-reused 1578
Receiving objects: 100% (2536/2536), 769.70 KiB | 9.39 MiB/s, done.
Resolving deltas: 100% (1807/1807), done.

(si) d:\repos>cd pykilosort

(si) d:\repos\pykilosort>pip install -r requirements.txt
Requirement already satisfied: click in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from -r requirements.txt (line 1)) (8.1.7)
Requirement already satisfied: cupy in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from -r requirements.txt (line 2)) (12.2.0)
Requirement already satisfied: matplotlib in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from -r requirements.txt (line 3)) (3.7.2)
Requirement already satisfied: mock in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from -r requirements.txt (line 4)) (5.1.0)
Requirement already satisfied: numba in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from -r requirements.txt (line 5)) (0.57.1)
Requirement already satisfied: numpy in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from -r requirements.txt (line 6)) (1.24.4)
Requirement already satisfied: ibl-neuropixel>=0.8.0 in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from -r requirements.txt (line 7)) (0.8.0)
Requirement already satisfied: phylib in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from -r requirements.txt (line 8)) (2.4.3)
Requirement already satisfied: pydantic in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from -r requirements.txt (line 9)) (2.0.3)
Requirement already satisfied: pytest in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from -r requirements.txt (line 10)) (7.4.1)
Requirement already satisfied: scipy in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from -r requirements.txt (line 11)) (1.11.2)
Requirement already satisfied: spikeinterface in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from -r requirements.txt (line 12)) (0.99.0.dev0)
Requirement already satisfied: tqdm in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from -r requirements.txt (line 13)) (4.66.1)
Requirement already satisfied: colorama in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from click->-r requirements.txt (line 1)) (0.4.6)
Requirement already satisfied: fastrlock>=0.5 in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from cupy->-r requirements.txt (line 2)) (0.8.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from matplotlib->-r requirements.txt (line 3)) (1.1.0)
Requirement already satisfied: cycler>=0.10 in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from matplotlib->-r requirements.txt (line 3)) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from matplotlib->-r requirements.txt (line 3)) (4.42.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from matplotlib->-r requirements.txt (line 3)) (1.4.5)
Requirement already satisfied: packaging>=20.0 in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from matplotlib->-r requirements.txt (line 3)) (23.1)
Requirement already satisfied: pillow>=6.2.0 in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from matplotlib->-r requirements.txt (line 3)) (10.0.0)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from matplotlib->-r requirements.txt (line 3)) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from matplotlib->-r requirements.txt (line 3)) (2.8.2)
Requirement already satisfied: llvmlite<0.41,>=0.40.0dev0 in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from numba->-r requirements.txt (line 5)) (0.40.1)
Requirement already satisfied: iblutil>=1.7.0 in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from ibl-neuropixel>=0.8.0->-r requirements.txt (line 7)) (1.7.0)
Requirement already satisfied: joblib in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from ibl-neuropixel>=0.8.0->-r requirements.txt (line 7)) (1.3.2)
Requirement already satisfied: mtscomp in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from ibl-neuropixel>=0.8.0->-r requirements.txt (line 7)) (1.0.2)
Requirement already satisfied: one-api in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from ibl-neuropixel>=0.8.0->-r requirements.txt (line 7)) (2.2.2)
Requirement already satisfied: pandas in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from ibl-neuropixel>=0.8.0->-r requirements.txt (line 7)) (2.1.0)
Requirement already satisfied: dask in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from phylib->-r requirements.txt (line 8)) (2023.9.1)
Requirement already satisfied: requests in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from phylib->-r requirements.txt (line 8)) (2.31.0)
Requirement already satisfied: toolz in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from phylib->-r requirements.txt (line 8)) (0.12.0)
Requirement already satisfied: annotated-types>=0.4.0 in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from pydantic->-r requirements.txt (line 9)) (0.5.0)
Requirement already satisfied: pydantic-core==2.3.0 in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from pydantic->-r requirements.txt (line 9)) (2.3.0)
Requirement already satisfied: typing-extensions>=4.6.1 in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from pydantic->-r requirements.txt (line 9)) (4.7.1)
Requirement already satisfied: iniconfig in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from pytest->-r requirements.txt (line 10)) (2.0.0)
Requirement already satisfied: pluggy<2.0,>=0.12 in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from pytest->-r requirements.txt (line 10)) (1.3.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc8 in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from pytest->-r requirements.txt (line 10)) (1.1.3)
Requirement already satisfied: tomli>=1.0.0 in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from pytest->-r requirements.txt (line 10)) (2.0.1)
Requirement already satisfied: neo>=0.12.0 in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from spikeinterface->-r requirements.txt (line 12)) (0.13.0.dev0)
Requirement already satisfied: threadpoolctl in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from spikeinterface->-r requirements.txt (line 12)) (3.2.0)
Requirement already satisfied: probeinterface>=0.2.17 in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from spikeinterface->-r requirements.txt (line 12)) (0.2.18)
Requirement already satisfied: colorlog>=6.0.0 in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from iblutil>=1.7.0->ibl-neuropixel>=0.8.0->-r requirements.txt (line 7)) (6.7.0)
Requirement already satisfied: pyarrow in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from iblutil>=1.7.0->ibl-neuropixel>=0.8.0->-r requirements.txt (line 7)) (13.0.0)
Requirement already satisfied: quantities>=0.14.1 in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from neo>=0.12.0->spikeinterface->-r requirements.txt (line 12)) (0.14.1)
Requirement already satisfied: pytz>=2020.1 in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from pandas->ibl-neuropixel>=0.8.0->-r requirements.txt (line 7)) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from pandas->ibl-neuropixel>=0.8.0->-r requirements.txt (line 7)) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from python-dateutil>=2.7->matplotlib->-r requirements.txt (line 3)) (1.16.0)
Requirement already satisfied: cloudpickle>=1.5.0 in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from dask->phylib->-r requirements.txt (line 8)) (2.2.1)
Requirement already satisfied: fsspec>=2021.09.0 in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from dask->phylib->-r requirements.txt (line 8)) (2023.9.0)
Requirement already satisfied: partd>=1.2.0 in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from dask->phylib->-r requirements.txt (line 8)) (1.4.0)
Requirement already satisfied: pyyaml>=5.3.1 in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from dask->phylib->-r requirements.txt (line 8)) (6.0.1)
Requirement already satisfied: importlib-metadata>=4.13.0 in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from dask->phylib->-r requirements.txt (line 8)) (6.8.0)
Requirement already satisfied: flake8>=3.7.8 in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from one-api->ibl-neuropixel>=0.8.0->-r requirements.txt (line 7)) (6.1.0)
Requirement already satisfied: boto3 in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from one-api->ibl-neuropixel>=0.8.0->-r requirements.txt (line 7)) (1.28.42)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from requests->phylib->-r requirements.txt (line 8)) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from requests->phylib->-r requirements.txt (line 8)) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from requests->phylib->-r requirements.txt (line 8)) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from requests->phylib->-r requirements.txt (line 8)) (2023.7.22)
Requirement already satisfied: mccabe<0.8.0,>=0.7.0 in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from flake8>=3.7.8->one-api->ibl-neuropixel>=0.8.0->-r requirements.txt (line 7)) (0.7.0)
Requirement already satisfied: pycodestyle<2.12.0,>=2.11.0 in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from flake8>=3.7.8->one-api->ibl-neuropixel>=0.8.0->-r requirements.txt (line 7)) (2.11.0)
Requirement already satisfied: pyflakes<3.2.0,>=3.1.0 in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from flake8>=3.7.8->one-api->ibl-neuropixel>=0.8.0->-r requirements.txt (line 7)) (3.1.0)
Requirement already satisfied: zipp>=0.5 in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from importlib-metadata>=4.13.0->dask->phylib->-r requirements.txt (line 8)) (3.16.2)
Requirement already satisfied: locket in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from partd>=1.2.0->dask->phylib->-r requirements.txt (line 8)) (1.0.0)
Requirement already satisfied: botocore<1.32.0,>=1.31.42 in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from boto3->one-api->ibl-neuropixel>=0.8.0->-r requirements.txt (line 7)) (1.31.42)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from boto3->one-api->ibl-neuropixel>=0.8.0->-r requirements.txt (line 7)) (1.0.1)
Requirement already satisfied: s3transfer<0.7.0,>=0.6.0 in c:\users\muhang\miniconda3\envs\si\lib\site-packages (from boto3->one-api->ibl-neuropixel>=0.8.0->-r requirements.txt (line 7)) (0.6.2)

(si) d:\repos\pykilosort>python setup.py install
C:\Users\muhang\miniconda3\envs\si\lib\site-packages\setuptools\dist.py:509: SetuptoolsDeprecationWarning: Invalid version: 'ibl_1.4.5'.
!!

        ********************************************************************************
        The version specified is not a valid version according to PEP 440.
        This may not work as expected with newer versions of
        setuptools, pip, and PyPI.

        By 2023-Sep-26, you need to update your project and remove deprecated calls
        or your builds will no longer be supported.

        See https://peps.python.org/pep-0440/ for details.
        ********************************************************************************

!!
  self._validate_version(self.metadata.version)
running install
C:\Users\muhang\miniconda3\envs\si\lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
C:\Users\muhang\miniconda3\envs\si\lib\site-packages\setuptools\_distutils\cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
C:\Users\muhang\miniconda3\envs\si\lib\site-packages\setuptools\command\egg_info.py:131: SetuptoolsDeprecationWarning: Invalid version: 'ibl_1.4.5'.
!!

        ********************************************************************************
        Version 'ibl_1.4.5' is not valid according to PEP 440.

        Please make sure to specify a valid version for your package.
        Also note that future releases of setuptools may halt the build process
        if an invalid version is given.

        By 2023-Sep-26, you need to update your project and remove deprecated calls
        or your builds will no longer be supported.

        See https://peps.python.org/pep-0440/ for details.
        ********************************************************************************

!!
  return _normalization.best_effort_version(tagged)
Traceback (most recent call last):
  File "d:\repos\pykilosort\setup.py", line 39, in <module>
    setup(
  File "C:\Users\muhang\miniconda3\envs\si\lib\site-packages\setuptools\__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\muhang\miniconda3\envs\si\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
  File "C:\Users\muhang\miniconda3\envs\si\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "C:\Users\muhang\miniconda3\envs\si\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "C:\Users\muhang\miniconda3\envs\si\lib\site-packages\setuptools\dist.py", line 1233, in run_command
    super().run_command(command)
  File "C:\Users\muhang\miniconda3\envs\si\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Users\muhang\miniconda3\envs\si\lib\site-packages\setuptools\command\install.py", line 84, in run
    self.do_egg_install()
  File "C:\Users\muhang\miniconda3\envs\si\lib\site-packages\setuptools\command\install.py", line 132, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\muhang\miniconda3\envs\si\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "C:\Users\muhang\miniconda3\envs\si\lib\site-packages\setuptools\dist.py", line 1233, in run_command
    super().run_command(command)
  File "C:\Users\muhang\miniconda3\envs\si\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
    cmd_obj.ensure_finalized()
  File "C:\Users\muhang\miniconda3\envs\si\lib\site-packages\setuptools\_distutils\cmd.py", line 111, in ensure_finalized
    self.finalize_options()
  File "C:\Users\muhang\miniconda3\envs\si\lib\site-packages\setuptools\command\bdist_egg.py", line 95, in finalize_options
    ei_cmd = self.ei_cmd = self.get_finalized_command("egg_info")
  File "C:\Users\muhang\miniconda3\envs\si\lib\site-packages\setuptools\_distutils\cmd.py", line 305, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "C:\Users\muhang\miniconda3\envs\si\lib\site-packages\setuptools\_distutils\cmd.py", line 111, in ensure_finalized
    self.finalize_options()
  File "C:\Users\muhang\miniconda3\envs\si\lib\site-packages\setuptools\command\egg_info.py", line 225, in finalize_options
    parsed_version = packaging.version.Version(self.egg_version)
  File "C:\Users\muhang\miniconda3\envs\si\lib\site-packages\setuptools\_vendor\packaging\version.py", line 198, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
**setuptools.extern.packaging.version.InvalidVersion: Invalid version: 'ibl-1.4.5'**

**Comment by chris-langfield** [comment]
Hi there, please `git fetch` and `git pull` on the same branch (`ibl_prod`). With version 1.4.6 this should go away.
