### ISSUE TITLE
[Bug report] Churchland lab spike sorting errors

### ISSUE THREAD

**Issue by oliche** [int-brain-lab/pykilosort#22]
I have run 14 sessions in total. 3 of them were completed. 11 of them failed. I notice there are 3 types of errors:
(1)  cupy_backends.cuda.libs.cublas.CUBLASError: CUBLAS_STATUS_NOT_INITIALIZED:
[SpikeSorting 38bdc37b-c8be-4f18-b0a2-8a22dfa5f47e CSHL069/2020-10-09/001 Errored | Change task | Alyx (](https://alyx.internationalbrainlab.org/admin/jobs/task/0de6ae1c-ae13-447a-9ad1-443b3a4c0523/change/)[internationalbrainlab.org](http://internationalbrainlab.org/)[)](https://alyx.internationalbrainlab.org/admin/jobs/task/0de6ae1c-ae13-447a-9ad1-443b3a4c0523/change/)
[SpikeSorting c875fc7d-0966-448a-813d-663088fbfae8 CSHL025/2020-10-08/001 Errored | Change task | Alyx (](https://alyx.internationalbrainlab.org/admin/jobs/task/faa20c98-f25a-40dc-9ebf-71e19d0d607f/change/)[internationalbrainlab.org](http://internationalbrainlab.org/)[)](https://alyx.internationalbrainlab.org/admin/jobs/task/faa20c98-f25a-40dc-9ebf-71e19d0d607f/change/)
[SpikeSorting fe0ecca9-9279-4ce6-bbfe-8b875d30d34b CSHL072/2020-10-09/001 Errored | Change task | Alyx (](https://alyx.internationalbrainlab.org/admin/jobs/task/846b8af8-4e98-4cf5-ab91-fe6e5c59b131/change/)[internationalbrainlab.org](http://internationalbrainlab.org/)[)](https://alyx.internationalbrainlab.org/admin/jobs/task/846b8af8-4e98-4cf5-ab91-fe6e5c59b131/change/)
[SpikeSorting a3470924-a5b0-4cee-a04e-7597d4a94f8d CSHL068/2020-10-05/001 Errored | Change task | Alyx (](https://alyx.internationalbrainlab.org/admin/jobs/task/4adfd39f-a31f-4b22-b2e1-d279e83c5dfb/change/)[internationalbrainlab.org](http://internationalbrainlab.org/)[)](https://alyx.internationalbrainlab.org/admin/jobs/task/4adfd39f-a31f-4b22-b2e1-d279e83c5dfb/change/)
(2) cupy_backends.cuda.api.driver.CUDADriverError: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
[SpikeSorting bb2153e7-1052-491e-a022-790e755c7a54 CSHL075/2020-10-12/001 Errored | Change task | Alyx (](https://alyx.internationalbrainlab.org/admin/jobs/task/d506d5f3-5f81-498d-b801-7918c09666ed/change/)[internationalbrainlab.org](http://internationalbrainlab.org/)[)](https://alyx.internationalbrainlab.org/admin/jobs/task/d506d5f3-5f81-498d-b801-7918c09666ed/change/)
(3) EOFError: EOF when reading a line
[SpikeSorting 7ae3865a-d8f4-4b73-938e-ddaec33f8bc6 CSHL062/2020-07-08/001 Errored | Change task | Alyx (](https://alyx.internationalbrainlab.org/admin/jobs/task/4c8627d7-6193-4741-8fd8-7aaf3e932e10/change/)[internationalbrainlab.org](http://internationalbrainlab.org/)[)](https://alyx.internationalbrainlab.org/admin/jobs/task/4c8627d7-6193-4741-8fd8-7aaf3e932e10/change/)
[SpikeSorting 9931191e-8056-4adc-a410-a4a93487423f CSHL_019/2020-03-12/001 Errored | Change task | Alyx (](https://alyx.internationalbrainlab.org/admin/jobs/task/23c92682-b168-43b8-8f77-d4a46f09a47c/change/)[internationalbrainlab.org](http://internationalbrainlab.org/)[)](https://alyx.internationalbrainlab.org/admin/jobs/task/23c92682-b168-43b8-8f77-d4a46f09a47c/change/)
[SpikeSorting ad8e802d-ce83-437a-865f-fa769762a602 CSHL065/2020-10-02/002 Started | Change task | Alyx (](https://alyx.internationalbrainlab.org/admin/jobs/task/5dee056b-b8e7-4ebc-a552-2563755079de/change/)[internationalbrainlab.org](http://internationalbrainlab.org/)[)](https://alyx.internationalbrainlab.org/admin/jobs/task/5dee056b-b8e7-4ebc-a552-2563755079de/change/)
[SpikeSorting c94463ed-57da-4f02-8406-46f2f03924f3 CSHL046/2020-06-18/002 Errored | Change task | Alyx (](https://alyx.internationalbrainlab.org/admin/jobs/task/fefc7ecc-9af6-4ae2-99e8-5fe9c4c53d0e/change/)[internationalbrainlab.org](http://internationalbrainlab.org/)[)](https://alyx.internationalbrainlab.org/admin/jobs/task/fefc7ecc-9af6-4ae2-99e8-5fe9c4c53d0e/change/)
[SpikeSorting 9b4f6a8d-c879-4348-aa7e-0b34f6c6dacb CSHL067/2020-09-30/002 Started | Change task | Alyx (](https://alyx.internationalbrainlab.org/admin/jobs/task/37ef6920-fa22-4109-824d-a6775cf5da57/change/)[internationalbrainlab.org](http://internationalbrainlab.org/)[)](https://alyx.internationalbrainlab.org/admin/jobs/task/37ef6920-fa22-4109-824d-a6775cf5da57/change/)
[SpikeSorting c90cdfa0-2945-4f68-8351-cb964c258725 CSHL_018/2020-03-16/002 Errored | Change task | Alyx (](https://alyx.internationalbrainlab.org/admin/jobs/task/c522e293-06da-44c1-87b3-c1b2ca7c93c4/change/)[internationalbrainlab.org](http://internationalbrainlab.org/)[)](https://alyx.internationalbrainlab.org/admin/jobs/task/c522e293-06da-44c1-87b3-c1b2ca7c93c4/change/)

**Comment by oliche** [comment]
I have run 14 sessions in total. 3 of them were completed. 11 of them failed. I notice there are 3 types of errors:
(1)  cupy_backends.cuda.libs.cublas.CUBLASError: CUBLAS_STATUS_NOT_INITIALIZED:
[SpikeSorting 38bdc37b-c8be-4f18-b0a2-8a22dfa5f47e CSHL069/2020-10-09/001 Errored | Change task | Alyx (](https://alyx.internationalbrainlab.org/admin/jobs/task/0de6ae1c-ae13-447a-9ad1-443b3a4c0523/change/)[internationalbrainlab.org](http://internationalbrainlab.org/)[)](https://alyx.internationalbrainlab.org/admin/jobs/task/0de6ae1c-ae13-447a-9ad1-443b3a4c0523/change/)
[SpikeSorting c875fc7d-0966-448a-813d-663088fbfae8 CSHL025/2020-10-08/001 Errored | Change task | Alyx (](https://alyx.internationalbrainlab.org/admin/jobs/task/faa20c98-f25a-40dc-9ebf-71e19d0d607f/change/)[internationalbrainlab.org](http://internationalbrainlab.org/)[)](https://alyx.internationalbrainlab.org/admin/jobs/task/faa20c98-f25a-40dc-9ebf-71e19d0d607f/change/)
[SpikeSorting fe0ecca9-9279-4ce6-bbfe-8b875d30d34b CSHL072/2020-10-09/001 Errored | Change task | Alyx (](https://alyx.internationalbrainlab.org/admin/jobs/task/846b8af8-4e98-4cf5-ab91-fe6e5c59b131/change/)[internationalbrainlab.org](http://internationalbrainlab.org/)[)](https://alyx.internationalbrainlab.org/admin/jobs/task/846b8af8-4e98-4cf5-ab91-fe6e5c59b131/change/)
[SpikeSorting a3470924-a5b0-4cee-a04e-7597d4a94f8d CSHL068/2020-10-05/001 Errored | Change task | Alyx (](https://alyx.internationalbrainlab.org/admin/jobs/task/4adfd39f-a31f-4b22-b2e1-d279e83c5dfb/change/)[internationalbrainlab.org](http://internationalbrainlab.org/)[)](https://alyx.internationalbrainlab.org/admin/jobs/task/4adfd39f-a31f-4b22-b2e1-d279e83c5dfb/change/)
(2) cupy_backends.cuda.api.driver.CUDADriverError: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
[SpikeSorting bb2153e7-1052-491e-a022-790e755c7a54 CSHL075/2020-10-12/001 Errored | Change task | Alyx (](https://alyx.internationalbrainlab.org/admin/jobs/task/d506d5f3-5f81-498d-b801-7918c09666ed/change/)[internationalbrainlab.org](http://internationalbrainlab.org/)[)](https://alyx.internationalbrainlab.org/admin/jobs/task/d506d5f3-5f81-498d-b801-7918c09666ed/change/)
(3) EOFError: EOF when reading a line
[SpikeSorting 7ae3865a-d8f4-4b73-938e-ddaec33f8bc6 CSHL062/2020-07-08/001 Errored | Change task | Alyx (](https://alyx.internationalbrainlab.org/admin/jobs/task/4c8627d7-6193-4741-8fd8-7aaf3e932e10/change/)[internationalbrainlab.org](http://internationalbrainlab.org/)[)](https://alyx.internationalbrainlab.org/admin/jobs/task/4c8627d7-6193-4741-8fd8-7aaf3e932e10/change/)
[SpikeSorting 9931191e-8056-4adc-a410-a4a93487423f CSHL_019/2020-03-12/001 Errored | Change task | Alyx (](https://alyx.internationalbrainlab.org/admin/jobs/task/23c92682-b168-43b8-8f77-d4a46f09a47c/change/)[internationalbrainlab.org](http://internationalbrainlab.org/)[)](https://alyx.internationalbrainlab.org/admin/jobs/task/23c92682-b168-43b8-8f77-d4a46f09a47c/change/)
[SpikeSorting ad8e802d-ce83-437a-865f-fa769762a602 CSHL065/2020-10-02/002 Started | Change task | Alyx (](https://alyx.internationalbrainlab.org/admin/jobs/task/5dee056b-b8e7-4ebc-a552-2563755079de/change/)[internationalbrainlab.org](http://internationalbrainlab.org/)[)](https://alyx.internationalbrainlab.org/admin/jobs/task/5dee056b-b8e7-4ebc-a552-2563755079de/change/)
[SpikeSorting c94463ed-57da-4f02-8406-46f2f03924f3 CSHL046/2020-06-18/002 Errored | Change task | Alyx (](https://alyx.internationalbrainlab.org/admin/jobs/task/fefc7ecc-9af6-4ae2-99e8-5fe9c4c53d0e/change/)[internationalbrainlab.org](http://internationalbrainlab.org/)[)](https://alyx.internationalbrainlab.org/admin/jobs/task/fefc7ecc-9af6-4ae2-99e8-5fe9c4c53d0e/change/)
[SpikeSorting 9b4f6a8d-c879-4348-aa7e-0b34f6c6dacb CSHL067/2020-09-30/002 Started | Change task | Alyx (](https://alyx.internationalbrainlab.org/admin/jobs/task/37ef6920-fa22-4109-824d-a6775cf5da57/change/)[internationalbrainlab.org](http://internationalbrainlab.org/)[)](https://alyx.internationalbrainlab.org/admin/jobs/task/37ef6920-fa22-4109-824d-a6775cf5da57/change/)
[SpikeSorting c90cdfa0-2945-4f68-8351-cb964c258725 CSHL_018/2020-03-16/002 Errored | Change task | Alyx (](https://alyx.internationalbrainlab.org/admin/jobs/task/c522e293-06da-44c1-87b3-c1b2ca7c93c4/change/)[internationalbrainlab.org](http://internationalbrainlab.org/)[)](https://alyx.internationalbrainlab.org/admin/jobs/task/c522e293-06da-44c1-87b3-c1b2ca7c93c4/change/)

**Comment by Fenying-Zang** [comment]
> Related: some sessions were recorded with option 4 probes (with fewer channels), see [here](https://int-brain-lab.slack.com/archives/CEM70EXTN/p1681468411130069) for an overview. @Fenying-Zang could you check if all of these eids share a specific error message?
> 
> ![image](https://user-images.githubusercontent.com/6636245/271293287-3c566c0e-b9a1-48d6-afa7-c7879603a91c.png)

I've checked. But it appears I didn't run those sessions.

**Comment by chris-langfield** [comment]
Noting I talked with @oliche in person and the 9 insertions above had a spike sorting issue which was already fixed as of January (`pykilosort` issue with the lower number of channels).

**Comment by anne-urai** [comment]
> Noting I talked with @oliche in person and the 9 insertions above had a spike sorting issue which was already fixed as of January (`pykilosort` issue with the lower number of channels).

Yes, indeed - sorry for the confusion! Our problem now is that we're trying to run `pykilosort` on a different set of sessions that have now been spike sorted with the old matlab `kilosort`, which is returning several errors (see list in the first post)

**Comment by chris-langfield** [comment]
No, sorry it was my confusion! I just wanted to have the note there so we know it isn't the current issue. Thanks!

**Comment by oliche** [comment]
Hello, 
Kicking the can down the road here: the Globus issues should be resolved by now with the latest releases of ONE / ibllib. 

I've set the following 9 tasks to waiting and if you could please check those this PM in your time zone  @chris-langfield 

SpikeSorting  9b4f6a8d-c879-4348-aa7e-0b34f6c6dacb CSHL067/2020-09-30/002  Waiting https://alyx.internationalbrainlab.org/admin/jobs/task/37ef6920-fa22-4109-824d-a6775cf5da57/change/
SpikeSorting  495bee7e-b58e-42ea-8481-4a1bfedca54a UCLA048/2022-08-19/001  Waiting https://alyx.internationalbrainlab.org/admin/jobs/task/c402e8b5-1861-49cb-b7be-80234cf47a4a/change/
SpikeSorting  ad8e802d-ce83-437a-865f-fa769762a602 CSHL065/2020-10-02/002  Waiting https://alyx.internationalbrainlab.org/admin/jobs/task/5dee056b-b8e7-4ebc-a552-2563755079de/change/
SpikeSorting  c94463ed-57da-4f02-8406-46f2f03924f3 CSHL046/2020-06-18/002  Waiting https://alyx.internationalbrainlab.org/admin/jobs/task/fefc7ecc-9af6-4ae2-99e8-5fe9c4c53d0e/change/
SpikeSorting  c90cdfa0-2945-4f68-8351-cb964c258725 CSHL_018/2020-03-16/002  Waiting https://alyx.internationalbrainlab.org/admin/jobs/task/c522e293-06da-44c1-87b3-c1b2ca7c93c4/change/
SpikeSorting  9931191e-8056-4adc-a410-a4a93487423f CSHL_019/2020-03-12/001  Waiting https://alyx.internationalbrainlab.org/admin/jobs/task/23c92682-b168-43b8-8f77-d4a46f09a47c/change/
SpikeSorting  0deb75fb-9088-42d9-b744-012fb8fc4afb CSHL053/2020-01-30/001  Waiting https://alyx.internationalbrainlab.org/admin/jobs/task/fd079d68-3177-40c5-9f30-12f1a4e134ee/change/
SpikeSorting  88d24c31-52e4-49cc-9f32-6adbeb9eba87 SWC_043/2020-09-19/001  Waiting https://alyx.internationalbrainlab.org/admin/jobs/task/db17e284-cb25-4c08-8040-d73237f82a18/change/
SpikeSorting  7ae3865a-d8f4-4b73-938e-ddaec33f8bc6 CSHL062/2020-07-08/001  Waiting https://alyx.internationalbrainlab.org/admin/jobs/task/4c8627d7-6193-4741-8fd8-7aaf3e932e10/change/

**Comment by chris-langfield** [comment]
As of now (1800 EST):

https://alyx.internationalbrainlab.org/admin/jobs/task/c402e8b5-1861-49cb-b7be-80234cf47a4a/change/
Globus error
https://alyx.internationalbrainlab.org/admin/jobs/task/5dee056b-b8e7-4ebc-a552-2563755079de/change/
CUDADriver error
https://alyx.internationalbrainlab.org/admin/jobs/task/db17e284-cb25-4c08-8040-d73237f82a18/change/
CUDADriver error

The rest are Started or Waiting

**Comment by chris-langfield** [comment]
As of today:
https://alyx.internationalbrainlab.org/admin/jobs/task/37ef6920-fa22-4109-824d-a6775cf5da57/change/
probe01: compressed chunk error
probe00: CUDA out of memory error

The others are complete

**Comment by chris-langfield** [comment]
The 4 sessions above are running on SDSC now, namely:
```
["UCLA048/2022-08-19/001",
 "CSHL065/2020-10-02/002",
 "SWC_043/2020-09-19/001",
 "CSHL067/2020-09-30/002"]
```

**Comment by chris-langfield** [comment]
`CSHL067/2020-09-30/002 probe01`: CUDA error
`UCLA048/2022-08-19/001 probe00`: CUDA error
The rest went through unscathed

**Comment by anne-urai** [comment]
I'm a bit confused there are `UCLA` mice here - I think the only ones to run should be from the `churchland_learninglifespan` project.. it should be these https://alyx.internationalbrainlab.org/ibl_reports/spikesorting?session__project=100cb662-dec2-4e2b-b71c-8ce2b4ba5698&status=1&page=2

**Comment by chris-langfield** [comment]
Probably @oliche added those to the list to rerun because they also suffered the Globus error?

**Comment by chris-langfield** [comment]
The following spike sorting runs have been restarted:

https://alyx.internationalbrainlab.org/admin/jobs/task/c402e8b5-1861-49cb-b7be-80234cf47a4a/change/
https://alyx.internationalbrainlab.org/admin/jobs/task/5dee056b-b8e7-4ebc-a552-2563755079de/change/
https://alyx.internationalbrainlab.org/admin/jobs/task/db17e284-cb25-4c08-8040-d73237f82a18/change/
https://alyx.internationalbrainlab.org/admin/jobs/task/37ef6920-fa22-4109-824d-a6775cf5da57/change/

From what I can tell these were the stragglers from this thread. @anne-urai let me know what else needs to be rerun thanks!

**Comment by chris-langfield** [comment]
From the slack thread, the following `lifelonglearning` sessions have errored spike sorting:

```
c875fc7d-0966-448a-813d-663088fbfae8 *
9b4f6a8d-c879-4348-aa7e-0b34f6c6dacb
bb2153e7-1052-491e-a022-790e755c7a54
fe0ecca9-9279-4ce6-bbfe-8b875d30d34b *
38bdc37b-c8be-4f18-b0a2-8a22dfa5f47e
a3470924-a5b0-4cee-a04e-7597d4a94f8d *

CSHL025/2020-10-08/001 *
CSHL067/2020-09-30/002
CSHL075/2020-10-12/001
CSHL072/2020-10-09/001 *
CSHL069/2020-10-09/001
CSHL068/2020-10-05/001 *
```

* https://alyx.internationalbrainlab.org/admin/jobs/task/faa20c98-f25a-40dc-9ebf-71e19d0d607f/change/
https://alyx.internationalbrainlab.org/admin/jobs/task/37ef6920-fa22-4109-824d-a6775cf5da57/change/
https://alyx.internationalbrainlab.org/admin/jobs/task/d506d5f3-5f81-498d-b801-7918c09666ed/change/
* https://alyx.internationalbrainlab.org/admin/jobs/task/846b8af8-4e98-4cf5-ab91-fe6e5c59b131/change/
https://alyx.internationalbrainlab.org/admin/jobs/task/0de6ae1c-ae13-447a-9ad1-443b3a4c0523/change/
* https://alyx.internationalbrainlab.org/admin/jobs/task/4adfd39f-a31f-4b22-b2e1-d279e83c5dfb/change/

Asterisk indicates the pykilosort 1.5.0 rerun has just been started. The rest have errored on the pykilosort rerun.

**Comment by anne-urai** [comment]
Hi all,

here is some current info on the spike sorting tasks of the lifespan project: [excel file](https://github.com/Fenying-Zang/noisy_aging/blob/master/data/IBL_lifespan_spikesorting_task_info_simple.xlsx), [code](https://github.com/Fenying-Zang/noisy_aging/blob/master/scripts/check_lifespan_spikesorting_info.py). 

We'd like all of our `learninglifespan` insertions to be spike-sorted with at least `pykilosort` (so *not* `ks_matlab`) so that we can compare neural activity in these old mice with young animals from the brainwide map.

Here is the **list of eids (n=57) that need pykilosort 1.5.0 spike sorting**: `['fe80df7d-15f0-4f89-9bbb-d3e5725c4b0a', '7ae3865a-d8f4-4b73-938e-ddaec33f8bc6', 'c875fc7d-0966-448a-813d-663088fbfae8', 'a0dfbbc6-0454-4dc6-ade0-9ba57c18241d', '6f87f78d-f091-46c7-8226-e8b1936b28ee', 'e71bd25a-8c1e-4751-8985-4463a91c1b66', '9b4f6a8d-c879-4348-aa7e-0b34f6c6dacb', 'bb2153e7-1052-491e-a022-790e755c7a54', '9931191e-8056-4adc-a410-a4a93487423f', '41dfdc2a-987a-402a-99ae-779d5f569566', '2eb86e84-4b48-488c-81ed-b98335d9a922', '48cdc3ce-8e21-4090-9686-e26c6e4e851f', '83292b0f-e30f-48e1-ad0a-6f2bfe04e8b0', 'a45e62df-9f7f-4429-95a4-c4e334c8209f', '5c936319-6829-41cb-abc7-c4430910a6a0', 'da9eeafc-d7af-4a19-bf1c-2064e5b1b696', '107249ca-0d03-4e56-a7eb-6fe6210550ae', 'a06189b0-a66e-4a5a-a1ef-4afa80de8b31', '150f92bc-e755-4f54-96c1-84e1eaf832b4', 'bf358c9a-ef84-4604-b83a-93416d2827ff', '022dd14c-eff2-470f-863c-e019fafa53ae', 'fe0ecca9-9279-4ce6-bbfe-8b875d30d34b', '308274fc-28e8-4bfd-a4e3-3903b7b48c28', '38bdc37b-c8be-4f18-b0a2-8a22dfa5f47e', 'b26295df-e78d-4368-b694-1bf584f25bfc', '531e7ac0-cfcd-4593-9bf7-bb7bab5d66e9', '3a1b819b-71ef-4d71-aae6-9f83c1f509cb', '9a14e9b7-0f79-410b-a456-1e8e7887e621', 'a68ef902-026c-4dfa-857f-8bc799a3b5e5', 'ded7c877-49cf-46ad-b726-741f1cf34cef', '78fceb60-e623-431b-ab80-7e29209058ac', '2d768cde-65d4-4374-af2e-6ff3bf606eb4', '945028b5-bb38-4379-8ae4-488bcd67bcf5', 'ab8a5331-1d0f-4b8a-9e0f-7be41c4857f9', '7aa9fe27-3f10-4ee0-a5a3-a0c59884f2b6', 'f31752a8-a6bb-498b-8118-6339d3d74ecb', '11cc0294-fbc5-44b7-8a2c-484daa64c81e', 'ba7fc4d0-0486-4415-9b12-3f13b1cff710', '804bc680-976b-4e3e-9a47-a7e94847bd06', '2cff323c-1510-4b78-a5d1-ca07b203f60c', '87b628a4-f11a-429c-ad98-34d43cf3178b', 'f45e30cf-12aa-4fa0-8248-f9f885dfa9ef', '6f321eab-6dad-4f2e-8160-5b182f999bb6', 'a44fd8cc-ae4c-49b2-a6b4-97c6552ad9f6', 'c90cdfa0-2945-4f68-8351-cb964c258725', '8cfb0b3d-2877-4616-9e32-4139c4501691', '89e258e9-cbca-4eca-bac4-13a2388b5113', 'c94463ed-57da-4f02-8406-46f2f03924f3', 'e38c3ca1-4c0e-4fac-bcaf-b94db6e1b8e0', 'a5145869-a54a-4871-95ef-016421122844', 'a3470924-a5b0-4cee-a04e-7597d4a94f8d', '27f3c7a6-7be5-40e2-b4d8-9393978aeae1', '93374502-c701-4b83-aa1a-23050b514708', 'af74b29d-a671-4c22-a5e8-1e3d27e362f3', '078fb4b2-4bff-414c-92a8-a2fb97ffcf59', 'f2545193-1c5c-420e-96ac-3cb4b9799ea5', '0fe99726-9982-4c41-a07c-2cd7af6a6733']`

We previously reset some of those tasks to `Waiting` ourselves, but got various CUDA errors. _How do you think we can best proceed? Shall we 1. set tasks to `Waiting again` and make a comprehensive overview of all errors, or 2. perhaps plan a meeting to look over them together and discuss the best approach?

**Comment by chris-langfield** [comment]
Consolidated cuda errors issue: https://github.com/int-brain-lab/pykilosort/issues/25
